[package]
name = "differential-equations"
version = "0.1.0-beta.1"
edition = "2024"
rust-version = "1.85"
description = "Beta Rust implementations of Julia SciML ODE solvers"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Wouittone/differential-equations-rs"
homepage = "https://github.com/Wouittone/differential-equations-rs"
documentation = "https://docs.rs/differential-equations"
include = [
    "/src/**/*.rs",
    "/coefficients/**/*.toml",
    "/tableaux/**/*.toml",
    "/README.md",
    "/LICENSE-APACHE",
    "/LICENSE-MIT",
    "/THIRD_PARTY_NOTICES.md",
]
publish = false

[workspace]
members = ["tableau-macros"]
resolver = "2"

[features]
default = ["parallel"]
allocation-metrics = []
parallel = ["dep:rayon"]

[dependencies]
differential-equations-tableau-macros = { version = "=0.1.0-beta.1", path = "tableau-macros" }
rayon = { version = "1.11.0", optional = true }
thiserror = "2.0.20"

[dev-dependencies]
stats_alloc = "0.1.10"
