schema_version = 1
name = "Heun"
description = "The adaptive second-order explicit trapezoid (Heun) method."
order = 2
embedded_order = 1
fsal = false

nodes = ["0", "1"]
coefficients = [[], ["1"]]
weights = ["1/2", "1/2"]
error_weights = ["-1/2", "1/2"]
