schema_version = 1
name = "Ralston"
description = "Ralston's adaptive second-order explicit Runge--Kutta method."
order = 2
embedded_order = 1
fsal = false

nodes = ["0", "2/3"]
coefficients = [[], ["2/3"]]
weights = ["1/4", "3/4"]
error_weights = ["-3/4", "3/4"]
