//! Compile-time validation and expansion of declarative solver tableau resources.

mod algorithms;
mod expansion;
mod input;
mod static_tableaus;

use proc_macro::TokenStream;

/// Defines a zero-sized explicit Runge--Kutta algorithm from a JSON resource.
///
/// The path is relative to the invoking package's `CARGO_MANIFEST_DIR`. The
/// file is parsed and validated while compiling. The expansion embeds the
/// source text and parses it lazily when the algorithm is first used; it does
/// not generate Rust coefficient arrays.
#[proc_macro]
pub fn define_explicit_rk_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_explicit_rk_from_file(input)
}

/// Defines a lazy implicit Runge--Kutta tableau static from a JSON resource.
///
/// The resource is parsed and validated during macro expansion. The emitted
/// static embeds only its source text and materializes coefficients on first
/// use, allowing specialized implicit kernels to share the canonical serde
/// representation without generated Rust constants.
#[proc_macro]
pub fn define_implicit_rk_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_implicit_rk_tableau_from_file(input)
}

/// Defines a lazy explicit Runge--Kutta tableau static from a JSON resource.
///
/// This form is intended for public compatibility aliases and specialized
/// kernels that cannot use the zero-sized algorithm generated by
/// [`define_explicit_rk_from_file!`].
#[proc_macro]
pub fn define_explicit_rk_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_explicit_rk_tableau_from_file(input)
}

/// Defines a lazy canonical linear multistep tableau from a JSON resource.
///
/// Accepts `visibility STATIC_NAME, "MethodName", "resource.json"` and an
/// optional `crate = local_name`. Validates coefficients and polynomial order
/// conditions at compile time, then embeds only source text for lazy parsing.
#[proc_macro]
pub fn define_multistep_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_multistep_tableau_from_file(input)
}

/// Defines a lazy variable-step two-step tableau from a JSON resource.
///
/// Coefficient functions, the startup formula, and the local-defect estimator
/// are validated during macro expansion. Only source text is embedded and the
/// tableau is materialized on first inspection or use.
#[proc_macro]
pub fn define_variable_multistep_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_variable_multistep_tableau_from_file(input)
}

/// Defines a lazy MRI-GARK tableau validated from a JSON resource.
#[proc_macro]
pub fn define_mri_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_mri_tableau_from_file(input)
}

/// Defines a lazy MIS coupling tableau validated from a JSON resource.
#[proc_macro]
pub fn define_mis_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_mis_tableau_from_file(input)
}

/// Defines a lazy Rosenbrock or hybrid tableau, validated at compile time.
///
/// Accepts `visibility STATIC, "MethodName", "resource.json", crate = local_name`.
/// Only source text is embedded; coefficient arrays are parsed on first use.
#[proc_macro]
pub fn define_rosenbrock_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_rosenbrock_tableau_from_file(input)
}

/// Defines the lazy low-storage Rosenbrock 2/3 pair from a JSON resource.
///
/// The resource is validated during macro expansion and embedded as source
/// text, then materialized only when one of the pair's solvers is first used.
#[proc_macro]
pub fn define_rosenbrock_pair_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_rosenbrock_pair_tableau_from_file(input)
}

/// Defines one lazily materialized RKN tableau from a validated JSON resource.
///
/// The resource is parsed during macro expansion for compile-time diagnostics.
/// The expansion embeds only its source text and parses it once on first use.
#[proc_macro]
pub fn define_rkn_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_rkn_tableau_from_file(input)
}

/// Defines one lazily materialized improved RKN tableau from validated JSON.
#[proc_macro]
pub fn define_irkn_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_irkn_tableau_from_file(input)
}

/// Defines one lazily materialized low-storage Runge--Kutta tableau.
///
/// The resource is parsed and validated during macro expansion. The emitted
/// static embeds only its source text and materializes coefficients on first
/// inspection or use.
#[proc_macro]
pub fn define_low_storage_rk_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_low_storage_rk_tableau_from_file(input)
}

/// Defines one independently lazy, degree-specific ROCK2 tableau.
///
/// The JSON resource is fully parsed and validated during macro expansion.
/// The expansion embeds the original source with `include_str!` and parses it
/// once, only when this particular degree is inspected or selected.
#[proc_macro]
pub fn define_rock2_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_rock2_tableau_from_file(input)
}

/// Defines one independently lazy, degree-specific ROCK4 tableau.
///
/// The shared parser validates the recurrence, finishing tableau, fourth-order
/// primary method, and third-order embedded companion during macro expansion.
#[proc_macro]
pub fn define_rock4_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_rock4_tableau_from_file(input)
}

/// Defines one independently lazy, degree-specific SERK2 tableau.
///
/// The shared parser reconstructs the recurrence and validates its second-order
/// conditions during macro expansion. The emitted static embeds only the JSON
/// source and parses it on first use.
#[proc_macro]
pub fn define_serk2_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_serk2_tableau_from_file(input)
}

/// Defines one independently lazy, degree-specific ESERK tableau.
///
/// The shared parser validates the stabilized recurrence and extrapolation
/// moments during macro expansion. The expansion embeds only the source JSON
/// and parses it when this particular degree is first selected or inspected.
#[proc_macro]
pub fn define_eserk_tableau_from_file(input: TokenStream) -> TokenStream {
    static_tableaus::define_eserk_tableau_from_file(input)
}

/// Defines a named fixed or adaptive RKN solver from one JSON resource.
///
/// The generated zero-sized type implements `SecondOrderOdeAlgorithm` and
/// exposes its independently lazy tableau through `tableau()`.
#[proc_macro]
pub fn define_rkn_from_file(input: TokenStream) -> TokenStream {
    algorithms::define_rkn_from_file(input)
}

/// Defines a named low-storage Runge--Kutta solver from one JSON resource.
///
/// The generated zero-sized type implements [`OdeAlgorithm`](https://docs.rs/differential-equations-rs/latest/differential_equations/trait.OdeAlgorithm.html)
/// and exposes its independently lazy tableau through `tableau()`.
#[proc_macro]
pub fn define_low_storage_rk_from_file(input: TokenStream) -> TokenStream {
    algorithms::define_low_storage_rk_from_file(input)
}

/// Defines a symplectic composition from a validated JSON resource.
///
/// Like [`define_explicit_rk_from_file!`], accepts a visibility, method name,
/// resource path, and optional `crate = path`. The expansion contains an
/// `include_str!` resource and a per-method lazy tableau, not coefficient arrays.
#[proc_macro]
pub fn define_symplectic_from_file(input: TokenStream) -> TokenStream {
    algorithms::define_symplectic_from_file(input)
}
