// Static-tableau macro implementations and validation tests.

use crate::algorithms::{
    expand, expand_irkn_source, expand_low_storage_rk_source, expand_rkn_source,
    expand_rosenbrock_source, expand_static,
};
use crate::expansion::{emit_lazy_static, expand_multistep_source, read_static_resource};
use crate::input::{
    DegreeStaticTableauInput, MacroInput, OrderDegreeStaticTableauInput, StaticTableauInput,
};

use differential_equations_tableau_core::{
    RungeKuttaKind, parse_eserk_tableau, parse_rock2_tableau, parse_rock4_tableau,
    parse_serk2_tableau,
};
use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use std::path::PathBuf;
use syn::parse_macro_input;

/// Defines a zero-sized explicit Runge--Kutta algorithm from a JSON resource.
///
/// The path is relative to the invoking package's `CARGO_MANIFEST_DIR`. The
/// file is parsed and validated while compiling. The expansion embeds the
/// source text and parses it lazily when the algorithm is first used; it does
/// not generate Rust coefficient arrays.
pub fn define_explicit_rk_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as MacroInput);
    match expand(input) {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

/// Defines a lazy implicit Runge--Kutta tableau static from a JSON resource.
///
/// The resource is parsed and validated during macro expansion. The emitted
/// static embeds only its source text and materializes coefficients on first
/// use, allowing specialized implicit kernels to share the canonical serde
/// representation without generated Rust constants.
pub fn define_implicit_rk_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as StaticTableauInput);
    match expand_static(input, RungeKuttaKind::Implicit) {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

/// Defines a lazy explicit Runge--Kutta tableau static from a JSON resource.
///
/// This form is intended for public compatibility aliases and specialized
/// kernels that cannot use the zero-sized algorithm generated by
/// [`define_explicit_rk_from_file!`].
pub fn define_explicit_rk_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as StaticTableauInput);
    match expand_static(input, RungeKuttaKind::Explicit) {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

/// Defines a lazy canonical linear multistep tableau from a JSON resource.
///
/// Accepts `visibility STATIC_NAME, "MethodName", "resource.json"` and an
/// optional `crate = local_name`. Validates coefficients and polynomial order
/// conditions at compile time, then embeds only source text for lazy parsing.
pub fn define_multistep_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as StaticTableauInput);
    let result =
        read_static_resource(&input).and_then(|source| expand_multistep_source(input, &source));
    match result {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

/// Defines a lazy variable-step two-step tableau from a JSON resource.
///
/// Coefficient functions, the startup formula, and the local-defect estimator
/// are validated during macro expansion. Only source text is embedded and the
/// tableau is materialized on first inspection or use.
pub fn define_variable_multistep_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as StaticTableauInput);
    let result = read_static_resource(&input).and_then(|source| {
        differential_equations_tableau_core::parse_variable_multistep_tableau(
            &source,
            &input.method_name.value(),
        )
        .map_err(|error| format!("invalid tableau `{}`: {error}", input.path.value()))?;
        Ok(emit_lazy_static(
            input,
            quote!(LazyVariableMultistepTableau),
            quote!(parse_variable_multistep_tableau),
        ))
    });
    match result {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

/// Defines a lazy MRI-GARK tableau validated from a JSON resource.
pub fn define_mri_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as StaticTableauInput);
    let result = read_static_resource(&input).and_then(|source| {
        differential_equations_tableau_core::parse_mri_tableau(&source, &input.method_name.value())
            .map_err(|error| format!("invalid tableau `{}`: {error}", input.path.value()))?;
        Ok(emit_lazy_static(
            input,
            quote!(LazyMriTableau),
            quote!(parse_mri_tableau),
        ))
    });
    match result {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

/// Defines a lazy MIS coupling tableau validated from a JSON resource.
pub fn define_mis_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as StaticTableauInput);
    let result = read_static_resource(&input).and_then(|source| {
        differential_equations_tableau_core::parse_mis_tableau(&source, &input.method_name.value())
            .map_err(|error| format!("invalid tableau `{}`: {error}", input.path.value()))?;
        Ok(emit_lazy_static(
            input,
            quote!(LazyMisTableau),
            quote!(parse_mis_tableau),
        ))
    });
    match result {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

/// Defines a lazy Rosenbrock or hybrid tableau, validated at compile time.
///
/// Accepts `visibility STATIC, "MethodName", "resource.json", crate = local_name`.
/// Only source text is embedded; coefficient arrays are parsed on first use.
pub fn define_rosenbrock_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as StaticTableauInput);
    match read_static_resource(&input).and_then(|source| expand_rosenbrock_source(input, &source)) {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

/// Defines the lazy low-storage Rosenbrock 2/3 pair from a JSON resource.
///
/// The resource is validated during macro expansion and embedded as source
/// text, then materialized only when one of the pair's solvers is first used.
pub fn define_rosenbrock_pair_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as StaticTableauInput);
    let result = read_static_resource(&input).and_then(|source| {
        differential_equations_tableau_core::parse_rosenbrock_pair_tableau(
            &source,
            &input.method_name.value(),
        )
        .map_err(|error| format!("invalid tableau `{}`: {error}", input.path.value()))?;
        Ok(emit_lazy_static(
            input,
            quote!(LazyRosenbrockPairTableau),
            quote!(parse_rosenbrock_pair_tableau),
        ))
    });
    match result {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

/// Defines one lazily materialized RKN tableau from a validated JSON resource.
///
/// The resource is parsed during macro expansion for compile-time diagnostics.
/// The expansion embeds only its source text and parses it once on first use.
pub fn define_rkn_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as StaticTableauInput);
    let result = read_static_resource(&input).and_then(|source| expand_rkn_source(input, &source));
    match result {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

/// Defines one lazily materialized improved RKN tableau from validated JSON.
pub fn define_irkn_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as StaticTableauInput);
    let result = read_static_resource(&input).and_then(|source| expand_irkn_source(input, &source));
    match result {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

/// Defines one lazily materialized low-storage Runge--Kutta tableau.
///
/// The resource is parsed and validated during macro expansion. The emitted
/// static embeds only its source text and materializes coefficients on first
/// inspection or use.
pub fn define_low_storage_rk_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as StaticTableauInput);
    let result = read_static_resource(&input)
        .and_then(|source| expand_low_storage_rk_source(input, &source));
    match result {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

/// Defines one independently lazy, degree-specific ROCK2 tableau.
///
/// The JSON resource is fully parsed and validated during macro expansion.
/// The expansion embeds the original source with `include_str!` and parses it
/// once, only when this particular degree is inspected or selected.
pub fn define_rock2_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DegreeStaticTableauInput);
    let result =
        read_degree_static_resource(&input).and_then(|source| expand_rock2_source(input, &source));
    match result {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

fn expand_rock2_source(
    input: DegreeStaticTableauInput,
    source: &str,
) -> Result<TokenStream2, String> {
    let degree = input
        .degree
        .base10_parse::<usize>()
        .map_err(|error| format!("invalid ROCK2 degree: {error}"))?;
    parse_rock2_tableau(source, &input.method_name.value(), degree)
        .map_err(|error| format!("invalid tableau `{}`: {error}", input.path.value()))?;

    Ok(emit_degree_lazy_static(
        input,
        degree,
        quote!(LazyRock2Tableau),
        quote!(parse_rock2_tableau),
    ))
}

/// Defines one independently lazy, degree-specific ROCK4 tableau.
///
/// The shared parser validates the recurrence, finishing tableau, fourth-order
/// primary method, and third-order embedded companion during macro expansion.
pub fn define_rock4_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DegreeStaticTableauInput);
    let result =
        read_degree_static_resource(&input).and_then(|source| expand_rock4_source(input, &source));
    match result {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

fn expand_rock4_source(
    input: DegreeStaticTableauInput,
    source: &str,
) -> Result<TokenStream2, String> {
    let degree = input
        .degree
        .base10_parse::<usize>()
        .map_err(|error| format!("invalid ROCK4 degree: {error}"))?;
    parse_rock4_tableau(source, &input.method_name.value(), degree)
        .map_err(|error| format!("invalid tableau `{}`: {error}", input.path.value()))?;
    Ok(emit_degree_lazy_static(
        input,
        degree,
        quote!(LazyRock4Tableau),
        quote!(parse_rock4_tableau),
    ))
}

/// Defines one independently lazy, degree-specific SERK2 tableau.
///
/// The shared parser reconstructs the recurrence and validates its second-order
/// conditions during macro expansion. The emitted static embeds only the JSON
/// source and parses it on first use.
pub fn define_serk2_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DegreeStaticTableauInput);
    let result =
        read_degree_static_resource(&input).and_then(|source| expand_serk2_source(input, &source));
    match result {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

fn expand_serk2_source(
    input: DegreeStaticTableauInput,
    source: &str,
) -> Result<TokenStream2, String> {
    let degree = input
        .degree
        .base10_parse::<usize>()
        .map_err(|error| format!("invalid SERK2 degree: {error}"))?;
    parse_serk2_tableau(source, &input.method_name.value(), degree)
        .map_err(|error| format!("invalid tableau '{}': {error}", input.path.value()))?;
    Ok(emit_degree_lazy_static(
        input,
        degree,
        quote!(LazySerk2Tableau),
        quote!(parse_serk2_tableau),
    ))
}

/// Defines one independently lazy, degree-specific ESERK tableau.
///
/// The shared parser validates the stabilized recurrence and extrapolation
/// moments during macro expansion. The expansion embeds only the source JSON
/// and parses it when this particular degree is first selected or inspected.
pub fn define_eserk_tableau_from_file(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as OrderDegreeStaticTableauInput);
    let result = read_order_degree_static_resource(&input)
        .and_then(|source| expand_eserk_source(input, &source));
    match result {
        Ok(tokens) => tokens.into(),
        Err(error) => syn::Error::new(proc_macro2::Span::call_site(), error)
            .into_compile_error()
            .into(),
    }
}

fn expand_eserk_source(
    input: OrderDegreeStaticTableauInput,
    source: &str,
) -> Result<TokenStream2, String> {
    let order = input
        .order
        .base10_parse::<usize>()
        .map_err(|error| format!("invalid ESERK order: {error}"))?;
    let degree = input
        .degree
        .base10_parse::<usize>()
        .map_err(|error| format!("invalid ESERK degree: {error}"))?;
    parse_eserk_tableau(source, &input.method_name.value(), order, degree)
        .map_err(|error| format!("invalid tableau '{}': {error}", input.path.value()))?;

    let visibility = input.visibility;
    let static_name = input.static_name;
    let method_name = input.method_name;
    let source_path = input.path;
    let crate_path = input.crate_path;
    Ok(quote! {
        #visibility static #static_name: #crate_path::tableau::LazyEserkTableau =
            ::std::sync::LazyLock::new(|| {
                #crate_path::tableau::parse_eserk_tableau(
                    include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/", #source_path)),
                    #method_name,
                    #order,
                    #degree,
                )
            });
    })
}

fn emit_degree_lazy_static(
    input: DegreeStaticTableauInput,
    degree: usize,
    lazy_type: TokenStream2,
    parser: TokenStream2,
) -> TokenStream2 {
    let visibility = input.visibility;
    let static_name = input.static_name;
    let method_name = input.method_name;
    let source_path = input.path;
    let crate_path = input.crate_path;
    quote! {
        #visibility static #static_name: #crate_path::tableau::#lazy_type =
            ::std::sync::LazyLock::new(|| {
                #crate_path::tableau::#parser(
                    include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/", #source_path)),
                    #method_name,
                    #degree,
                )
            });
    }
}

fn read_degree_static_resource(input: &DegreeStaticTableauInput) -> Result<String, String> {
    let manifest_dir = std::env::var_os("CARGO_MANIFEST_DIR")
        .map(PathBuf::from)
        .ok_or("CARGO_MANIFEST_DIR is unavailable during macro expansion")?;
    let path = manifest_dir.join(input.path.value());
    std::fs::read_to_string(&path)
        .map_err(|error| format!("failed to read `{}`: {error}", path.display()))
}

fn read_order_degree_static_resource(
    input: &OrderDegreeStaticTableauInput,
) -> Result<String, String> {
    let manifest_dir = std::env::var_os("CARGO_MANIFEST_DIR")
        .map(PathBuf::from)
        .ok_or("CARGO_MANIFEST_DIR is unavailable during macro expansion")?;
    let path = manifest_dir.join(input.path.value());
    std::fs::read_to_string(&path)
        .map_err(|error| format!("failed to read `{}`: {error}", path.display()))
}

#[cfg(test)]
mod rock2_tests {
    use super::*;

    fn source() -> &'static str {
        r#"{
            "name":"ROCK2",
            "description":"Macro test",
            "kind":"rock2",
            "order":2,
            "degree":2,
            "recurrence":{
                "first":"0.09326607661089206",
                "stages":[["0.1268473641290642","0.02103378190528467"]]
            },
            "finishing":{
                "first":"0.3889624104727243",
                "second":"0.4219428123056774"
            }
        }"#
    }

    fn input() -> DegreeStaticTableauInput {
        syn::parse_str("pub TABLEAU, \"ROCK2\", 2, \"degree.json\", crate = renamed").unwrap()
    }

    #[test]
    fn expansion_embeds_only_the_validated_source() {
        let tokens = expand_rock2_source(input(), source()).unwrap().to_string();
        assert!(tokens.contains("LazyRock2Tableau"));
        assert!(tokens.contains("LazyLock"));
        assert!(tokens.contains("include_str"));
        assert!(tokens.contains("parse_rock2_tableau"));
        assert!(tokens.contains("renamed"));
        assert!(!tokens.contains("0.09326607661089206"));
        assert!(!tokens.contains("0.3889624104727243"));
        assert!(!tokens.contains("const "));
    }

    #[test]
    fn expansion_reports_resource_identity_and_shape_errors() {
        for invalid in [
            source().replace(r#""degree":2"#, r#""degree":3"#),
            source().replace(r#""name":"ROCK2""#, r#""name":"ROCK4""#),
            source().replace(
                r#"["0.1268473641290642","0.02103378190528467"]"#,
                r#"["0.1268473641290642"]"#,
            ),
        ] {
            let error = expand_rock2_source(input(), &invalid).unwrap_err();
            assert!(error.contains("degree.json"), "{error}");
        }
    }
}

#[cfg(test)]
mod rock4_tests {
    use super::*;

    fn source() -> &'static str {
        r#"{
            "name":"ROCK4",
            "description":"Macro test",
            "kind":"rock4",
            "order":4,
            "embedded_order":3,
            "degree":1,
            "recurrence":{"first":"0.1762962957651941","stages":[]},
            "finishing":{
                "A":[[],["-0.149352078672699"],["0.629768962985252","-0.35520106157365"],["0.0146745996307541","-0.0558517281602565","0.590312931352706"]],
                "b":["0.934502625489809","-0.426556402801135","-0.428612609028723","0.744370090574855"],
                "b_hat":["1.1350997211054","-0.58433336098972","-0.319172911177732","0.482853558185876","0.109256697110981"]
            }
        }"#
    }

    fn input() -> DegreeStaticTableauInput {
        syn::parse_str("pub TABLEAU, \"ROCK4\", 1, \"rock4.json\", crate = renamed").unwrap()
    }

    #[test]
    fn expansion_uses_the_shared_lazy_parser_without_emitting_coefficients() {
        let tokens = expand_rock4_source(input(), source()).unwrap().to_string();
        for required in [
            "LazyRock4Tableau",
            "LazyLock",
            "include_str",
            "parse_rock4_tableau",
            "renamed",
        ] {
            assert!(tokens.contains(required), "missing {required}: {tokens}");
        }
        assert!(!tokens.contains("0.1762962957651941"));
        assert!(!tokens.contains("0.934502625489809"));
        assert!(!tokens.contains("const "));
    }

    #[test]
    fn expansion_rejects_an_invalid_order_formula_with_its_path() {
        let invalid = source().replace("0.934502625489809", "0.9");
        let error = expand_rock4_source(input(), &invalid).unwrap_err();
        assert!(error.contains("rock4.json"), "{error}");
        assert!(error.contains("order condition"), "{error}");
    }
}

#[cfg(test)]
mod serk2_tests {
    use super::*;

    fn source() -> &'static str {
        r#"{
            "name":"SERK2",
            "description":"Macro test",
            "kind":"serk2",
            "order":2,
            "degree":2,
            "alpha":"2.5 / 4",
            "subdivisions":1,
            "weights":["1.32","-0.96","0.64"]
        }"#
    }

    fn input() -> DegreeStaticTableauInput {
        syn::parse_str("pub TABLEAU, \"SERK2\", 2, \"serk2.json\", crate = renamed").unwrap()
    }

    #[test]
    fn expansion_uses_the_shared_lazy_parser_without_emitting_coefficients() {
        let tokens = expand_serk2_source(input(), source()).unwrap().to_string();
        for required in [
            "LazySerk2Tableau",
            "LazyLock",
            "include_str",
            "parse_serk2_tableau",
            "renamed",
        ] {
            assert!(tokens.contains(required), "missing {required}: {tokens}");
        }
        assert!(!tokens.contains("1.32"));
        assert!(!tokens.contains("- 0.96"));
        assert!(!tokens.contains("const "));
    }

    #[test]
    fn expansion_rejects_invalid_metadata_and_order_conditions() {
        for invalid in [
            source().replace(r#""degree":2"#, r#""degree":3"#),
            source().replace(r#""name":"SERK2""#, r#""name":"OTHER""#),
            source().replace("0.64", "0.63"),
        ] {
            let error = expand_serk2_source(input(), &invalid).unwrap_err();
            assert!(error.contains("serk2.json"), "{error}");
        }
    }
}

#[cfg(test)]
mod eserk_tests {
    use super::*;

    fn source() -> &'static str {
        r#"{
            "name":"ESERK4",
            "description":"Synthetic degree-one extrapolated stabilized method",
            "kind":"eserk",
            "order":4,
            "embedded_order":3,
            "degree":1,
            "internal_degree":1,
            "alpha":"1",
            "subdivisions":4,
            "solution_combination":[-1,24,-81,64],
            "error_combination":[-1,12,-27,16],
            "combination_denominator":"6",
            "weights":["0","1"]
        }"#
    }

    fn input() -> OrderDegreeStaticTableauInput {
        syn::parse_str("pub TABLEAU, \"ESERK4\", 4, 1, \"eserk.json\", crate = renamed").unwrap()
    }

    #[test]
    fn expansion_embeds_only_the_validated_source() {
        let tokens = expand_eserk_source(input(), source()).unwrap().to_string();
        for required in [
            "LazyEserkTableau",
            "LazyLock",
            "include_str",
            "parse_eserk_tableau",
            "renamed",
        ] {
            assert!(tokens.contains(required), "missing {required}: {tokens}");
        }
        for forbidden in ["0.129", "Vec", "from (["] {
            assert!(!tokens.contains(forbidden), "emitted {forbidden}: {tokens}");
        }
    }

    #[test]
    fn expansion_rejects_invalid_metadata_and_moments() {
        for invalid in [
            source().replace(r#""order":4"#, r#""order":5"#),
            source().replace(r#""degree":1"#, r#""degree":2"#),
            source().replace("[-1,24,-81,64]", "[-1,24,-81,63]"),
            source().replace("[-1,12,-27,16]", "[0,0,0,0]"),
        ] {
            let error = expand_eserk_source(input(), &invalid).unwrap_err();
            assert!(error.contains("eserk.json"), "{error}");
        }
    }
}
