"""Generate GJ8 ordinate coefficients from Berry & Healy (2004).

Exact Fraction arithmetic. c are coefficients of L(z)=-z/log(1-z).
B_corrector = (L-1)/z. A_corrector = (L^2-1+z)/z^2.
Predictor uses E=1/(1-z): B=(E L-1)/z; A=(E L^2-1)/z^2.
Backward differences z^i expand into the nine acceleration ordinates.
No implementation code from external integrators is incorporated.
"""
from fractions import Fraction as F
from math import comb
from pathlib import Path
c = [F(1)]
for n in range(1, 11):
    c.append(-sum(c[i] / (n+1-i) for i in range(n)))
d = [sum(c[j] * c[i-j] for j in range(i+1)) for i in range(11)]
def ordinates(coefficients):
    return [sum(coefficients[i] * (-1)**(8-k) * comb(i, 8-k) for i in range(8-k, 9)) for k in range(9)]
def shift_back_four(values):
    return [sum(F((-1)**k * comb(4,k))*values[i-k] for k in range(min(i,4)+1)) for i in range(9)]
rows = {'VELOCITY_CENTER': ordinates(shift_back_four(c[1:10])),
        'POSITION_CENTER': ordinates(shift_back_four(d[2:11])),
        'VELOCITY_CORRECTOR': ordinates(c[1:10]),
        'POSITION_CORRECTOR': ordinates(d[2:11]),
        'VELOCITY_PREDICTOR': ordinates([sum(c[:i+2]) for i in range(9)]),
        'POSITION_PREDICTOR': ordinates([sum(d[:i+3]) for i in range(9)])}
text = '// Generated by scripts/gauss_jackson_coefficients.py; exact rational derivation.\n'
for name, row in rows.items():
    text += 'pub(super) const '+name+': [f64; 9] = [\n'
    text += ''.join(f'    {x.numerator}.0 / {x.denominator}.0,\n' for x in row)
    text += '];\n'
Path('src/gauss_jackson/coefficients.rs').write_text(text)
