using OrdinaryDiffEqRKN
using Printf
using TOML

const PINNED_REVISION = "211142263781255a9aa2f910f6760b9f18ec29c8"
manifest = TOML.parsefile(joinpath(dirname(Base.active_project()), "Manifest.toml"))
rkn_manifest = only(manifest["deps"]["OrdinaryDiffEqRKN"])
get(rkn_manifest, "repo-rev", nothing) == PINNED_REVISION || error(
    "OrdinaryDiffEqRKN must be pinned at $(PINNED_REVISION)",
)

const METHODS = (
    ("DPRKN4", OrdinaryDiffEqRKN.DPRKN4Tableau, 4),
    ("DPRKN5", OrdinaryDiffEqRKN.DPRKN5Tableau, 5),
    ("DPRKN6FM", OrdinaryDiffEqRKN.DPRKN6FMTableau, 6),
    ("DPRKN8", OrdinaryDiffEqRKN.DPRKN8Tableau, 8),
    ("DPRKN12", OrdinaryDiffEqRKN.DPRKN12Tableau, 12),
    ("ERKN4", OrdinaryDiffEqRKN.ERKN4Tableau, 4),
    ("ERKN5", OrdinaryDiffEqRKN.ERKN5Tableau, 5),
    ("ERKN7", OrdinaryDiffEqRKN.ERKN7Tableau, 7),
)

const VELOCITY_DEPENDENT_METHODS = (
    ("FINERKN4", OrdinaryDiffEqRKN.FineRKN4Tableau, 4),
    ("FINERKN5", OrdinaryDiffEqRKN.FineRKN5Tableau, 5),
)

function rust_float(value::Float64)
    text = @sprintf("%.17g", value)
    if !occursin(r"[.eE]", text)
        text *= ".0"
    end
    replace(text, "e+" => "e")
end

function emit_array(io, name, values)
    println(io, "pub(crate) const $(name): &[f64] = &[")
    for value in values
        println(io, "    $(rust_float(value)),")
    end
    println(io, "];\n")
end

output = joinpath(@__DIR__, "..", "src", "rkn_adaptive_coefficients.rs")
open(output, "w") do io
    println(io, "// @generated by scripts/generate_rkn_adaptive_coefficients.jl")
    println(io, "// OrdinaryDiffEq.jl revision 211142263781255a9aa2f910f6760b9f18ec29c8.\n")
    println(io, "#![allow(clippy::excessive_precision)]\n")
    for (name, constructor, order) in METHODS
        tableau = constructor(Float64, Float64)
        prefix = uppercase(name)
        stages = length(tableau.b)
        # Julia matrices are column-major; emit row-major for the Rust kernel.
        emit_array(io, "$(prefix)_A", [tableau.a[row, column] for row in 1:stages for column in 1:stages])
        emit_array(io, "$(prefix)_B", tableau.b)
        emit_array(io, "$(prefix)_BP", tableau.bp)
        emit_array(io, "$(prefix)_BTILDE", tableau.btilde)
        emit_array(io, "$(prefix)_BPTILDE", tableau.bptilde)
        emit_array(io, "$(prefix)_C", vcat(0.0, tableau.c))
        println(io, "pub(crate) const $(prefix)_ORDER: usize = $(order);")
        println(io, "pub(crate) const $(prefix)_POS_ONLY_ERROR: bool = $(tableau.pos_only_error);\n")
    end
    for (prefix, constructor, order) in VELOCITY_DEPENDENT_METHODS
        tableau = constructor(Float64, Float64)
        stages = length(tableau.b)
        emit_array(io, "$(prefix)_A", [tableau.a[row, column] for row in 1:stages for column in 1:stages])
        emit_array(io, "$(prefix)_ABAR", [tableau.abar[row, column] for row in 1:stages for column in 1:stages])
        emit_array(io, "$(prefix)_B", tableau.b)
        emit_array(io, "$(prefix)_BP", tableau.bp)
        emit_array(io, "$(prefix)_BTILDE", tableau.btilde)
        emit_array(io, "$(prefix)_BPTILDE", tableau.bptilde)
        emit_array(io, "$(prefix)_C", vcat(0.0, tableau.c))
        println(io, "pub(crate) const $(prefix)_ORDER: usize = $(order);")
        println(io, "pub(crate) const $(prefix)_POS_ONLY_ERROR: bool = false;\n")
    end
    tableau = OrdinaryDiffEqRKN.DPRKN6Tableau(Float64, Float64)
    stages = length(tableau.b)
    emit_array(io, "DPRKN6_A", [tableau.a[row, column] for row in 1:stages for column in 1:stages])
    emit_array(io, "DPRKN6_B", tableau.b)
    emit_array(io, "DPRKN6_BP", tableau.bp)
    emit_array(io, "DPRKN6_BTILDE", tableau.btilde)
    emit_array(io, "DPRKN6_BPTILDE", tableau.bptilde)
    emit_array(io, "DPRKN6_C", vcat(0.0, tableau.c))
    emit_array(io, "DPRKN6_R", [tableau.R[row, column] for row in 1:stages for column in 1:5])
    emit_array(io, "DPRKN6_RP", [tableau.Rp[row, column] for row in 1:stages for column in 1:5])
    println(io, "pub(crate) const DPRKN6_ORDER: usize = 6;")
    println(io, "pub(crate) const DPRKN6_POS_ONLY_ERROR: bool = false;\n")
end

# Keep the generated source byte-identical to the checked-in rustfmt form.
run(`rustfmt $output`)
